# Generated by Django 4.1.1 on 2022-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('NATURE', 'Nature'), ('EDUCATION', 'Education'), ('PETS AND ANIMALS', 'Pets and animals'), ('TECHNOLOGY', 'Technology'), ('FASHION', 'Fashion'), ('ENTERTAINMENT', 'Entertainment'), ('MOVIES', 'Movies'), ('GAMING', 'Gaming'), ('MUSIC', 'Music'), ('SPORTS', 'Sports'), ('NEWS', 'News'), ('TRAVEL', 'Travel'), ('COMEDY', 'Comedy'), ('DESIGN_AND_DEVELOPMENT', 'Design and Development'), ('FOOD_AND_DRINKS', 'Food and Drinks'), ('LIFESTYLE', 'Lifestyle'), ('HEALTH_AND_FITNESS', 'Health and Fitness'), ('BUSINESS', 'Business'), ('SHOPPING', 'Shopping'), ('ANIMATIONS', 'Animations')], max_length=50),
        ),
    ]
