# Generated by Django 4.1.1 on 2022-10-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='image/default.jpg', upload_to='image/'),
        ),
    ]
