# Generated by Django 4.1.1 on 2022-10-13 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='comments',
            name='blog_commen_date_po_e130af_idx',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='date_posted',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['created'], name='blog_commen_created_ad0231_idx'),
        ),
    ]
